### ISSUE TITLE
Error in using learncode.js

### ISSUE THREAD

**Issue by Beejeedeb** [sogaani/broadlink-adapter#9]
Hi I get the following error following the manual. I am using Raspberry PI 3 with Webthing version 0.92.

pi@gateway:~/.mozilla-iot/addons/broadlink-adapter $ node asset/learncode.js
module.js:550
    throw err;
    ^

Error: Cannot find module 'gateway-addon'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/.mozilla-iot/addons/broadlink-adapter/ir-property.js:3:30)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

**Comment by Beejeedeb** [comment]
After some more testing I see that a lot of modules are missing, I added them manually and it works. So please can you add the necessary node-modules and update the add-on.

**Comment by Beejeedeb** [comment]
@mrstegeman what should be done with add-ons which aren't active supported anymore. This add-on needs modules to work.

**Comment by mrstegeman** [comment]
If you (or someone else) is up for maintaining this add-on, I'd gladly replace this add-on with a fork in our add-on list.

However, to solve the issue above, you simply need to do the following:
```sh
NODE_PATH=~/mozilla-iot/gateway/node_modules node asset/learncode.js
```

The `gateway-addon` module is always provided by the gateway, rather than individual add-ons.

**Comment by Beejeedeb** [comment]
@mrstegeman  Thanks for the tip. I'm halfway through a Python course. When I finish the course I try to make a simple add-on. If this succeeds then I want to make an add-on to connect a bleutooth speaker as a thing on the Webthings gateway. And then I have enough confidence to help improve this add-on :-)
